### ISSUE TITLE
Binary not stripped

### ISSUE THREAD

**Issue by fantomfp** [Syndace/libxeddsa#4]
Binary is not stripped after build.

```
bin/libcombined_dynamic.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=1c702e015defe665d58e814bb5f9da8d12cc5cf7, with debug_info, not stripped
```

Version: 2.0.0

Please fix.

**Comment by Syndace** [comment]
Hey, first of all the name `libcombined` indicates that you are not using the newest build scripts. Second, what does stripping do and why would I need it?

**Comment by Syndace** [comment]
Nvm I found the relevant info. There's a `make install/strip` target already which installs stripped binaries, you can use that.
