### ISSUE TITLE
Updated ed25519 implementations

### ISSUE THREAD

**Issue by bkmgit** [Syndace/libxeddsa#7]
Consider using an updated implementation. See:
- https://github.com/novifinancial/ed25519-speccheck
- https://github.com/MystenLabs/ed25519-unsafe-libs

**Comment by Syndace** [comment]
Thank you for bringing this up. This library does not expose public API where private key/seed and public key can be passed in separately to the sign functions, the public key is always derived from the private key/seed right before signing. Thus, this library is not susceptible to the Double Public Key Signing Function Oracle Attack. The underlying libsodium isn't affected either.
